import type CustomerRegistrationStepInterface from '#model_management/type_checking/customer_registration_step/customer_registration_step_interface'
import type CreateNewRecordGeneric from '#common/type_checkings/model_management/create_new_record_generic'

type CreateCustomerRegistrationStepRecordPayload = Partial<CustomerRegistrationStepInterface>

type CreateCustomerRegistrationStepRecordOptions =
  CreateNewRecordGeneric<CreateCustomerRegistrationStepRecordPayload>

export default CreateCustomerRegistrationStepRecordOptions
