import type PopularLocationInterface from '#model_management/type_checking/popular_location/popular_location_interface'
import type CreateNewRecordGeneric from '#common/type_checkings/model_management/create_new_record_generic'

type CreatePopularLocationRecordPayload = Partial<PopularLocationInterface>

type CreatePopularLocationRecordOptions = CreateNewRecordGeneric<CreatePopularLocationRecordPayload>

export default CreatePopularLocationRecordOptions
