import type DriverLocationInterface from '#model_management/type_checking/driver_location/driver_location_interface'
import type CreateNewRecordGeneric from '#common/type_checkings/model_management/create_new_record_generic'

type CreateDriverLocationRecordPayload = Partial<DriverLocationInterface>

type CreateDriverLocationRecordOptions = CreateNewRecordGeneric<CreateDriverLocationRecordPayload>

export default CreateDriverLocationRecordOptions
