import type VehicleModelInterface from '#model_management/type_checking/vehicle_model/vehicle_model_interface'
import type CreateNewRecordGeneric from '#common/type_checkings/model_management/create_new_record_generic'

type CreateVehicleModelRecordPayload = Partial<VehicleModelInterface>

type CreateVehicleModelRecordOptions = CreateNewRecordGeneric<CreateVehicleModelRecordPayload>

export default CreateVehicleModelRecordOptions
