/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  v1: {
    admin: {
      authentication: {
        AuthenticateAdmin: () => import('#controllers/v1/admin/authentication/authenticate_admin_controller'),
      },
      customerManagement: {
        FetchCustomers: () => import('#controllers/v1/admin/customer_management/fetch_customers_controller'),
        GetCustomer: () => import('#controllers/v1/admin/customer_management/get_customer_controller'),
      },
      driverManagement: {
        FetchDrivers: () => import('#controllers/v1/admin/driver_management/fetch_drivers_controller'),
        GetDriver: () => import('#controllers/v1/admin/driver_management/get_driver_controller'),
      },
    },
    common: {
      finance: {
        FetchBanks: () => import('#controllers/v1/common/finance/fetch_banks_controller'),
      },
      location: {
        FetchCities: () => import('#controllers/v1/common/location/fetch_cities_controller'),
      },
      media: {
        UploadImage: () => import('#controllers/v1/common/media/upload_image_controller'),
      },
      vehicle: {
        FetchVehicleMakes: () => import('#controllers/v1/common/vehicle/fetch_vehicle_makes_controller'),
        FetchVehicleModels: () => import('#controllers/v1/common/vehicle/fetch_vehicle_models_controller'),
      },
    },
    customer: {
      accountActivation: {
        RequestAccountActivationToken: () => import('#controllers/v1/customer/account_activation/request_account_activation_token_controller'),
        VerifyAccountActivationToken: () => import('#controllers/v1/customer/account_activation/verify_account_activation_token_controller'),
      },
      authentication: {
        AuthenticateCustomer: () => import('#controllers/v1/customer/authentication/authenticate_customer_controller'),
        Onboarding: () => import('#controllers/v1/customer/authentication/onboarding_controller'),
      },
      passwordManagement: {
        resetPassword: {
          RequestResetPasswordOtpToken: () => import('#controllers/v1/customer/password_management/reset_password/request_reset_password_otp_token_controller'),
          ResetPassword: () => import('#controllers/v1/customer/password_management/reset_password/reset_password_controller'),
        },
      },
    },
    driver: {
      accountActivation: {
        RequestAccountActivationToken: () => import('#controllers/v1/driver/account_activation/request_account_activation_token_controller'),
        VerifyAccountActivationToken: () => import('#controllers/v1/driver/account_activation/verify_account_activation_token_controller'),
      },
      authentication: {
        AuthenticateDriver: () => import('#controllers/v1/driver/authentication/authenticate_driver_controller'),
        Onboarding: () => import('#controllers/v1/driver/authentication/onboarding_controller'),
      },
      passwordManagement: {
        resetPassword: {
          RequestResetPasswordOtpToken: () => import('#controllers/v1/driver/password_management/reset_password/request_reset_password_otp_token_controller'),
          ResetPassword: () => import('#controllers/v1/driver/password_management/reset_password/reset_password_controller'),
        },
      },
      profile: {
        bankAccount: {
          GetBankAccount: () => import('#controllers/v1/driver/profile/bank_account/get_bank_account_controller'),
          UpdateBankAccount: () => import('#controllers/v1/driver/profile/bank_account/update_bank_account_controller'),
        },
        documents: {
          GetDocuments: () => import('#controllers/v1/driver/profile/documents/get_documents_controller'),
          UpdateDocuments: () => import('#controllers/v1/driver/profile/documents/update_documents_controller'),
        },
        personalInformation: {
          GetPersonalInformation: () => import('#controllers/v1/driver/profile/personal_information/get_personal_information_controller'),
          UpdatePersonalInformation: () => import('#controllers/v1/driver/profile/personal_information/update_personal_information_controller'),
        },
        vehicleInformation: {
          GetVehicleInformation: () => import('#controllers/v1/driver/profile/vehicle_information/get_vehicle_information_controller'),
          UpdateVehicleInformation: () => import('#controllers/v1/driver/profile/vehicle_information/update_vehicle_information_controller'),
        },
      },
    },
  },
}
