/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  v1: {
    admin: {
      authentication: {
        AuthenticateAdmin: () => import('#controllers/v1/admin/authentication/authenticate_admin_controller'),
      },
      bookingManagement: {
        AssignBookingDriver: () => import('#controllers/v1/admin/booking_management/assign_booking_driver_controller'),
        CancelBooking: () => import('#controllers/v1/admin/booking_management/cancel_booking_controller'),
        CompleteBooking: () => import('#controllers/v1/admin/booking_management/complete_booking_controller'),
        FetchBookings: () => import('#controllers/v1/admin/booking_management/fetch_bookings_controller'),
        GetBooking: () => import('#controllers/v1/admin/booking_management/get_booking_controller'),
      },
      customerManagement: {
        FetchCustomers: () => import('#controllers/v1/admin/customer_management/fetch_customers_controller'),
        GetCustomer: () => import('#controllers/v1/admin/customer_management/get_customer_controller'),
      },
      driverManagement: {
        ApproveDriver: () => import('#controllers/v1/admin/driver_management/approve_driver_controller'),
        FetchDrivers: () => import('#controllers/v1/admin/driver_management/fetch_drivers_controller'),
        GetDriver: () => import('#controllers/v1/admin/driver_management/get_driver_controller'),
        RejectDriver: () => import('#controllers/v1/admin/driver_management/reject_driver_controller'),
      },
      settings: {
        booking: {
          popularLocations: {
            CreatePopularLocation: () => import('#controllers/v1/admin/settings/booking/popular_locations/create_popular_location_controller'),
            FetchPopularLocations: () => import('#controllers/v1/admin/settings/booking/popular_locations/fetch_popular_locations_controller'),
            GetPopularLocation: () => import('#controllers/v1/admin/settings/booking/popular_locations/get_popular_location_controller'),
            UpdatePopularLocation: () => import('#controllers/v1/admin/settings/booking/popular_locations/update_popular_location_controller'),
          },
          rideTypes: {
            CreateRideType: () => import('#controllers/v1/admin/settings/booking/ride_types/create_ride_type_controller'),
            FetchRideTypes: () => import('#controllers/v1/admin/settings/booking/ride_types/fetch_ride_types_controller'),
            GetRideType: () => import('#controllers/v1/admin/settings/booking/ride_types/get_ride_type_controller'),
            UpdateRideType: () => import('#controllers/v1/admin/settings/booking/ride_types/update_ride_type_controller'),
          },
        },
      },
    },
    common: {
      booking: {
        FetchPopularLocations: () => import('#controllers/v1/common/booking/fetch_popular_locations_controller'),
        FetchRideTypes: () => import('#controllers/v1/common/booking/fetch_ride_types_controller'),
      },
      finance: {
        FetchBanks: () => import('#controllers/v1/common/finance/fetch_banks_controller'),
        ProcessPaystackWebhook: () => import('#controllers/v1/common/finance/process_paystack_webhook_controller'),
      },
      location: {
        FetchCities: () => import('#controllers/v1/common/location/fetch_cities_controller'),
      },
      media: {
        UploadImage: () => import('#controllers/v1/common/media/upload_image_controller'),
      },
      vehicle: {
        FetchVehicleMakes: () => import('#controllers/v1/common/vehicle/fetch_vehicle_makes_controller'),
        FetchVehicleModels: () => import('#controllers/v1/common/vehicle/fetch_vehicle_models_controller'),
      },
    },
    customer: {
      accountActivation: {
        RequestAccountActivationToken: () => import('#controllers/v1/customer/account_activation/request_account_activation_token_controller'),
        VerifyAccountActivationToken: () => import('#controllers/v1/customer/account_activation/verify_account_activation_token_controller'),
      },
      authentication: {
        AuthenticateCustomer: () => import('#controllers/v1/customer/authentication/authenticate_customer_controller'),
        Onboarding: () => import('#controllers/v1/customer/authentication/onboarding_controller'),
      },
      booking: {
        CheckoutBookingWithCard: () => import('#controllers/v1/customer/booking/checkout_booking_with_card_controller'),
        CreateBooking: () => import('#controllers/v1/customer/booking/create_booking_controller'),
        FetchBookings: () => import('#controllers/v1/customer/booking/fetch_bookings_controller'),
        GetBooking: () => import('#controllers/v1/customer/booking/get_booking_controller'),
      },
      notifications: {
        FetchNotifications: () => import('#controllers/v1/customer/notifications/fetch_notifications_controller'),
        MarkNotificationAsRead: () => import('#controllers/v1/customer/notifications/mark_notification_as_read_controller'),
      },
      passwordManagement: {
        resetPassword: {
          RequestResetPasswordOtpToken: () => import('#controllers/v1/customer/password_management/reset_password/request_reset_password_otp_token_controller'),
          ResetPassword: () => import('#controllers/v1/customer/password_management/reset_password/reset_password_controller'),
        },
      },
    },
    driver: {
      accountActivation: {
        RequestAccountActivationToken: () => import('#controllers/v1/driver/account_activation/request_account_activation_token_controller'),
        VerifyAccountActivationToken: () => import('#controllers/v1/driver/account_activation/verify_account_activation_token_controller'),
      },
      authentication: {
        AuthenticateDriver: () => import('#controllers/v1/driver/authentication/authenticate_driver_controller'),
        Onboarding: () => import('#controllers/v1/driver/authentication/onboarding_controller'),
      },
      bookingManagement: {
        AcceptBooking: () => import('#controllers/v1/driver/booking_management/accept_booking_controller'),
        FetchBookings: () => import('#controllers/v1/driver/booking_management/fetch_bookings_controller'),
        GetBooking: () => import('#controllers/v1/driver/booking_management/get_booking_controller'),
        RejectBooking: () => import('#controllers/v1/driver/booking_management/reject_booking_controller'),
        UpdateBookingTripProgress: () => import('#controllers/v1/driver/booking_management/update_booking_trip_progress_controller'),
      },
      notifications: {
        FetchNotifications: () => import('#controllers/v1/driver/notifications/fetch_notifications_controller'),
        MarkNotificationAsRead: () => import('#controllers/v1/driver/notifications/mark_notification_as_read_controller'),
      },
      passwordManagement: {
        resetPassword: {
          RequestResetPasswordOtpToken: () => import('#controllers/v1/driver/password_management/reset_password/request_reset_password_otp_token_controller'),
          ResetPassword: () => import('#controllers/v1/driver/password_management/reset_password/reset_password_controller'),
        },
      },
      profile: {
        bankAccount: {
          GetBankAccount: () => import('#controllers/v1/driver/profile/bank_account/get_bank_account_controller'),
          UpdateBankAccount: () => import('#controllers/v1/driver/profile/bank_account/update_bank_account_controller'),
        },
        documents: {
          GetDocuments: () => import('#controllers/v1/driver/profile/documents/get_documents_controller'),
          UpdateDocuments: () => import('#controllers/v1/driver/profile/documents/update_documents_controller'),
        },
        personalInformation: {
          GetPersonalInformation: () => import('#controllers/v1/driver/profile/personal_information/get_personal_information_controller'),
          UpdatePersonalInformation: () => import('#controllers/v1/driver/profile/personal_information/update_personal_information_controller'),
        },
        vehicleInformation: {
          GetVehicleInformation: () => import('#controllers/v1/driver/profile/vehicle_information/get_vehicle_information_controller'),
          UpdateVehicleInformation: () => import('#controllers/v1/driver/profile/vehicle_information/update_vehicle_information_controller'),
        },
      },
    },
  },
}
