import DriverDocumentInterface from '#model_management/type_checking/driver_document/driver_document_interface'
import CreateNewRecordGeneric from '#common/type_checkings/model_management/create_new_record_generic'

type CreateDriverDocumentRecordPayload = Partial<DriverDocumentInterface>

type CreateDriverDocumentRecordOptions = CreateNewRecordGeneric<CreateDriverDocumentRecordPayload>

export default CreateDriverDocumentRecordOptions
