/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdminSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'firstName', 'id', 'identifier', 'lastName', 'password', 'updatedAt'] as const
  $columns = AdminSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column()
  declare lastName: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BankSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'identifier', 'name', 'updatedAt'] as const
  $columns = BankSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CitySchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'identifier', 'name', 'updatedAt'] as const
  $columns = CitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomerRegistrationStepSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'deletedAt', 'hasActivatedAccount', 'id', 'identifier', 'updatedAt'] as const
  $columns = CustomerRegistrationStepSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerId: number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare hasActivatedAccount: boolean | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomerSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'fcmToken', 'firstName', 'id', 'identifier', 'lastName', 'mobileNumber', 'password', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare fcmToken: string | null
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column()
  declare lastName: string | null
  @column()
  declare mobileNumber: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DriverBankAccountSchema extends BaseModel {
  static $columns = ['accountName', 'accountNumber', 'bankId', 'createdAt', 'deletedAt', 'driverId', 'id', 'identifier', 'updatedAt'] as const
  $columns = DriverBankAccountSchema.$columns
  @column()
  declare accountName: string | null
  @column()
  declare accountNumber: string | null
  @column()
  declare bankId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare driverId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DriverDocumentSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'driverId', 'driverLicenceUrl', 'id', 'identifier', 'passportPhotographUrl', 'updatedAt', 'vehiclePaperUrl', 'vehiclePhotoUrl'] as const
  $columns = DriverDocumentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare driverId: number | null
  @column()
  declare driverLicenceUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column()
  declare passportPhotographUrl: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehiclePaperUrl: string | null
  @column()
  declare vehiclePhotoUrl: string | null
}

export class DriverPersonalInformationSchema extends BaseModel {
  static $columns = ['cityId', 'createdAt', 'dateOfBirth', 'deletedAt', 'driverId', 'gender', 'homeAddress', 'id', 'identifier', 'nationalIdentificationNumber', 'updatedAt'] as const
  $columns = DriverPersonalInformationSchema.$columns
  @column()
  declare cityId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare dateOfBirth: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare driverId: number | null
  @column()
  declare gender: string | null
  @column()
  declare homeAddress: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column()
  declare nationalIdentificationNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DriverRegistrationStepSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'deletedAt', 'hasActivatedAccount', 'hasProvidedPersonalInformation', 'hasProvidedRequiredDocuments', 'hasProvidedVehicleInformation', 'id', 'identifier', 'updatedAt'] as const
  $columns = DriverRegistrationStepSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerId: number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare hasActivatedAccount: boolean | null
  @column()
  declare hasProvidedPersonalInformation: boolean | null
  @column()
  declare hasProvidedRequiredDocuments: boolean | null
  @column()
  declare hasProvidedVehicleInformation: boolean | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DriverVehicleSchema extends BaseModel {
  static $columns = ['colorOfVehicle', 'createdAt', 'deletedAt', 'driverId', 'id', 'identifier', 'plateNumber', 'seatCapacity', 'typeOfVehicle', 'updatedAt', 'vehicleMakeId', 'vehicleModelId'] as const
  $columns = DriverVehicleSchema.$columns
  @column()
  declare colorOfVehicle: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare driverId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column()
  declare plateNumber: string | null
  @column()
  declare seatCapacity: number | null
  @column()
  declare typeOfVehicle: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleMakeId: number | null
  @column()
  declare vehicleModelId: number | null
}

export class DriverSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'firstName', 'id', 'identifier', 'lastName', 'mobileNumber', 'password', 'updatedAt'] as const
  $columns = DriverSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column()
  declare lastName: string | null
  @column()
  declare mobileNumber: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OtpTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'expiresAt', 'id', 'identifier', 'purpose', 'status', 'token', 'updatedAt'] as const
  $columns = OtpTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column()
  declare purpose: string | null
  @column()
  declare status: string | null
  @column()
  declare token: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VehicleMakeSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'identifier', 'name', 'updatedAt'] as const
  $columns = VehicleMakeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VehicleModelSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'identifier', 'name', 'updatedAt', 'vehicleMakeId'] as const
  $columns = VehicleModelSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string | null
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleMakeId: number | null
}
