import type DriverRegistrationStepInterface from '#model_management/type_checking/driver_registration_step/driver_registration_step_interface'
import type CreateNewRecordGeneric from '#common/type_checkings/model_management/create_new_record_generic'

type CreateDriverRegistrationStepRecordPayload = Partial<DriverRegistrationStepInterface>

type CreateDriverRegistrationStepRecordOptions =
  CreateNewRecordGeneric<CreateDriverRegistrationStepRecordPayload>

export default CreateDriverRegistrationStepRecordOptions
