/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/bank_list_config.ts" />
/// <reference path="../../config/cache.ts" />
/// <reference path="../../config/card_payment_config.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/image_upload_config.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/mail.ts" />
/// <reference path="../../config/media_upload_config.ts" />
/// <reference path="../../config/push_notification_config.ts" />
/// <reference path="../../config/queue.ts" />
/// <reference path="../../config/redis.ts" />
