await import('#start/routes/v1/driver/authentication.routes')
await import('#start/routes/v1/driver/account_activation.routes')
await import('#start/routes/v1/driver/password_management.routes')
await import('#start/routes/v1/driver/profile.routes')
await import('#start/routes/v1/driver/notification.routes')
await import('#start/routes/v1/driver/booking.routes')
