import BookingPaymentInterface from '#model_management/type_checking/booking_payment/booking_payment_interface'
import CreateNewRecordGeneric from '#common/type_checkings/model_management/create_new_record_generic'

type CreateBookingPaymentRecordPayload = Partial<BookingPaymentInterface>

type CreateBookingPaymentRecordOptions = CreateNewRecordGeneric<CreateBookingPaymentRecordPayload>

export default CreateBookingPaymentRecordOptions
