import UpdateRecordGeneric from '#common/type_checkings/model_management/update_record_generic'
import BookingPaymentIdentifierOptions from '#model_management/type_checking/booking_payment/booking_payment_identifier_options'
import BookingPaymentInterface from '#model_management/type_checking/booking_payment/booking_payment_interface'

type UpdateBookingPaymentRecordOptions = UpdateRecordGeneric<
  BookingPaymentIdentifierOptions,
  Partial<BookingPaymentInterface>
>

export default UpdateBookingPaymentRecordOptions
