await import('#start/routes/v1/admin/authentication.routes')
await import('#start/routes/v1/admin/customer_management.routes')
await import('#start/routes/v1/admin/driver_management.routes')
await import('#start/routes/v1/admin/settings.routes')
await import('#start/routes/v1/admin/booking_management.routes')
await import('#start/routes/v1/admin/driver_wallet_management.routes')
